include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # - lib/main.dart # This is an example
  errors:
    avoid_print: error
    prefer_single_quotes: warning
    constant_identifier_names: info
    always_use_package_imports: error
    unnecessary_statements: info
    lines_longer_than_80_chars: warning
    avoid_empty_else: warning
    empty_catches: warning
    file_names: ignore

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    constant_identifier_names: false
    always_use_package_imports: true
    unnecessary_statements: true
    lines_longer_than_80_chars: true
    avoid_empty_else: true
    empty_catches: true
    file_names: false 
    curly_braces_in_flow_control_structures: false