name: control_panel
description: This repository contains the source code for the UI of the command board.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  web_socket_channel: ^2.4.0
  wifi_info_flutter: ^2.0.2
  fl_chart: ^0.66.2
  collection: ^1.17.2
  http: ^1.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  readmore: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica/Helvetica.ttf
        - asset: fonts/Helvetica/Helvetica-Oblique.ttf
        - asset: fonts/Helvetica/Helvetica-Bold.ttf
